### PR TITLE
Gradle plugin use the 'services' property

### PR DESCRIPTION
**Pull request by matthewmcnew**

### CODE REVIEW

**Comment by bentarnoff** [comment]
Hey @matthewmcnew have you signed and submitted the CLA? As explained above, all pull request submitters must have a CLA on-file with us. Please follow the instructions above, and let us know when you've submitted the CLA. Thanks.

**Comment by matthewmcnew** [comment]
@bentarnoff Do I still need to do this as Pivotal employee?

**Comment by bentarnoff** [comment]
@matthewmcnew Nope! But it looks like our bot isn't able to see your membership. Try following the instructions here: https://help.github.com/articles/publicizing-or-hiding-organization-membership/

**Comment by bentarnoff** [comment]
Thanks, @matthewmcnew !

**Pull request merged**
