### PR TITLE
Adding documentation about deploying applications and standardizing format

### PR DESCRIPTION
**Pull request by jvshahid**
Move documentation about deploying applications from buildpacks README to cf docs

[#118094267]

Signed-off-by: John Shahid <jvshahid@gmail.com>

### CODE REVIEW

**Comment by jbheron** [comment]
Thanks, @jvshahid!

**Comment by jncd** [comment]
Hi Jess,
Should this PR have been folded into pre-release?
- j

**Comment by jvshahid** [comment]
@jncd why ? the only change in this pr is to move **existing** documentation from the buildpack README to this repo.

**Comment by kimahoff** [comment]
Hi @jvshahid -- we are in the middle of a bit of internal housekeeping ATM. The question about duplicating the content into pre-release is mostly to do with that. Carry on.

**Comment by jvshahid** [comment]
Thanks @kimahoff for the clarification.

**Pull request merged**
