### PR TITLE
fixed broken links on python page

### PR DESCRIPTION
**Pull request by jmtaysom**

### CODE REVIEW

**Comment by ljarzynski** [comment]
Hi @jmtaysom, we appreciate your fix! Let me know when you sign the CLA using cfdreddbot's instructions so that I can close, reopen, and merge your PR! Thanks!

**Comment by jmtaysom** [comment]
I submitted my CLA. I dont know if I should expect a reply or not, but it is done on my end.

**Comment by chipchilders** [comment]
@ljarzynski We have received and filed @jmtaysom 's CLA. You can go ahead and merge.

**Comment by jmtaysom** [comment]
@ljarzynski is there anything else that you need from me for this pull request?

**Comment by animatedmax** [comment]
Thank you, jmtaysom !

**Pull request merged**
