### PR TITLE
Updated nodejs buildpack docs:

### PR DESCRIPTION
**Pull request by astrieanna**
- Clarify how to select yarn
- Give more information about offline vendoring and usage
[#159302357, #159291499]

Signed-off-by: Andrew Meyer <ameyer@pivotal.io>

### CODE REVIEW

**Comment by astrieanna** [comment]
Going to try again for CLA.

**Comment by astrieanna** [comment]
@ameyer-pivotal Also works at Pivotal. I'll bug him to publicize his org membership when he's back from vacation. This PR is actually fine to merge.

**Comment by bentarnoff** [comment]
Hey @astrieanna I think cfdreddbot is acting up because @ameyer-pivotal hasn't publicized their org membership?

**Comment by bentarnoff** [comment]
@astrieanna Perfect, thanks!

**Pull request merged**
