### PR TITLE
Add section for server side rendering

### PR DESCRIPTION
**Pull request by djoyahoy**

### CODE REVIEW

**Comment by djoyahoy** [comment]
@ndon55555 is a Pivotal intern so they should be covered by the CLA.

**Comment by bentarnoff** [comment]
Thanks @djoyahoy. @ndon55555 can I ask you to publicize your org membership? More info [here](https://help.github.com/articles/publicizing-or-hiding-organization-membership/).

**Comment by ndon55555** [comment]
Hi @bentarnoff, I've just publicized my org membership.

**Comment by bentarnoff** [comment]
Thanks @djoyahoy

**Comment by djoyahoy** [comment]
Thank you @bentarnoff!

**Pull request merged**
