### PR TITLE
Add docs for .NET buildpack

### PR DESCRIPTION
**Pull request by mastertinner**
I copied most of it from the buildpack's website. We'd need to update the links as soon as the buildpack is moved from the uncubator space into the official one.

### CODE REVIEW

**Comment by sclevine** [comment]
The buildpack is called the ".Net Core Buildpack," not the ".Net Buildpack."

**Comment by bentarnoff** [comment]
Thanks, @mastertinner. I've looped in @jncd and she will review this.

**Comment by mastertinner** [comment]
Thanks for your feedback, guys! I changed the name from ".NET Buildpack" to ".NET Core Buildpack"

**Comment by pspinrad** [comment]
Thanks, mastertinner!  We (PCF docs) may be in touch with q's.

**Comment by pspinrad** [comment]
Hey @mastertinner-- a few hopefully-quick questions:

1. Under what circumstances to you need to set the app listening port to $PORT?  Do you always have to do this, or only with apps based on templates in the cli-samples  repo or provided by Visual Studio and Yeoman?

2. How do the steps listed (changes to the `Main` and `project.json`) configure the listening port?

3. Do those steps do anything else besides configure the listening port?

3. Is there a .NET buildpack, and if so, why would people use the .NET Core buildpack instead?

Thanks!

**Comment by mastertinner** [comment]
Thanks for your valid questions, @pspinrad. I tried to answer them in #103.

**Pull request merged**
