### PR TITLE
Github -> GitHub

### PR DESCRIPTION
**Pull request by bbodenmiller**

### CODE REVIEW

**Comment by bentarnoff** [comment]
Thanks @bbodenmiller! Please see the instructions above for submitting a CLA so that we can get this PR merged.

**Comment by bbodenmiller** [comment]
I have to physical print and manually fill out then scan this form? That's ridiculous.

**Comment by christopherclark** [comment]
@bbodenmiller  Cloud Foundry will have a shiny new automated CLA process in place later this year.  In the meantime, some pdf work is required, I'm afraid.  Sorry for the inconvenience!  We are working to rectify this...

**Comment by animatedmax** [comment]
Hi @bbodenmiller
While we cannot accept a PR without a signed CLA, we have corrected the capitalization of all instances of "GitHub" in this repository.

Thank you for bringing this issue to our attention.

**Pull request closed without merging**
