### PR TITLE
adding version note to ruby operator doc

### PR DESCRIPTION
**Pull request by Dannyzen**

### CODE REVIEW

**Comment by abbyachau** [comment]
Thanks, @Dannyzen! If you make your org membership public, you'll stop getting these CLA notices. Thanks again!

Abby

**Comment by Dannyzen** [comment]
@abbyachau I think dredbot has some issues. Membership has been public for a while :(

**Comment by bsnchan** [comment]
@Dannyzen It looks like your membership is not public. If you go to your github profile, you should see the "Organizations" under your profile pic (See mine for reference https://github.com/bsnchan). You can follow the instructions here https://help.github.com/articles/publicizing-or-hiding-organization-membership/ to publicize your membership.

**Comment by cf-buildpacks-eng** [comment]
Thanks for the help!

**Pull request merged**
