### PR TITLE
Contribute CF documentation for the PHP CNB

### PR DESCRIPTION
**Pull request by dmikusa-pivotal**
Hi, this is a contribution with documentation for the new PHP buildpack that is based on the Cloud-Native PHP Buildpacks.

### CODE REVIEW

**Comment by jncd** [comment]
Hi @dmikusa-pivotal 
We didn't see this until today. It looks like the PM did the merge so it didn't appear on Docs radar. 
I noticed that this doesn't appear in any subnavs. Is it intentionally hidden right now? 
Do you have time this week for a chat? I've been looking it over, starting to correct typos, etc.
Cheers, Jane

**Comment by dmikusa-pivotal** [comment]
@jncd - Thanks for following up. I forgot to submit the PR for the subnavs. Sending that through shortly.

**Comment by jncd** [comment]
@dmikusa-pivotal Hi Dan, Thanks for the subnav. It looked really good. 

A few more questions for you (They'll continue to trickle in — let me know if you'd prefer to meet and review them all, or get a long batch of them at once.)

(1) http://docs-cloudfoundry-staging.cfapps.io/buildpacks/php-cnb/index.html#supported_software The cross-ref doesn't reference any CNB buildpacks. Is that as it should be? I had expected to see some reference to CNB on that page. 

(2) Should the new buildpack appear in the table of buildpacks? http://docs-cloudfoundry-staging.cfapps.io/buildpacks/system-buildpacks.html

**Comment by jncd** [comment]
(3) http://docs-cloudfoundry-staging.cfapps.io/buildpacks/php-cnb/php-config.html#options 
The default got left out of this cell. 😞 
Screen Shot 2020-03-03 at 3 30 53 PM

Now, I really want to know what the default is — it's a cliff hanger.

**Comment by dmikusa-pivotal** [comment]
>(1) http://docs-cloudfoundry-staging.cfapps.io/buildpacks/php-cnb/index.html#supported_software The cross-ref doesn't reference any CNB buildpacks. Is that as it should be? I had expected to see some reference to CNB on that page.

I wasn't totally sure what to put in this section, so I mentioned the information about the PHP dependencies we ship. That links to the existing buildpack because we are not currently publishing good release notes with this information. That should change at some point in the future and we can change the link then.

Not sure what else might be good to put here though. Do you have a good example of what we're doing elsewhere?

>(2) Should the new buildpack appear in the table of buildpacks? http://docs-cloudfoundry-staging.cfapps.io/buildpacks/system-buildpacks.html

That's a good question. My thought would be that we only list one buildpack there, and it's the currently active/recommended buildpack. There's going to be a transition period for the PHP CNB, so once it takes over and is the recommended buildpack then we just update the table to point to it instead of the existing PHP buildpack. @kvedurmu - what do you think? 

(3) http://docs-cloudfoundry-staging.cfapps.io/buildpacks/php-cnb/php-config.html#options
The default got left out of this cell. 😞

Good catch & I think it depends. Maybe something like this would work: `To preserve backward compatibility, the compatibility layer of the buildpack will set Apache HTTPD as the default. If you have migrated your app and are no longer depending on the compatibility layer then PHP's built-in web server is the default.` Does that seem to explain things clearly?

**Comment by jncd** [comment]
Hi @dmikusa-pivotal 
Thanks for all these answers. I'll update that first cell (3). And take no action on (1) or (2) yet — but good to understand about the system buildpacks. (I had the same question about the new CF-compatible Node.js CNB.)

**Pull request merged**
