### PR TITLE
Document location_include in the Staticfile buildpack

### PR DESCRIPTION
**Pull request by dgodd**
[#140852637]

Signed-off-by: Dave Goddard <dave@goddard.id.au>

### CODE REVIEW

**Comment by ljarzynski** [comment]
@dgodd Thanks for the PR! One quick thing before merging... would you be able to clarify what the difference is between the "custom location configuration" row and the "custom nginx configuration" row in the table? Are they related?

**Comment by dgodd** [comment]
@ljarzynski  They are related. 

"custom nginx configuration" replaces the **entire** config file

"custom location configuration" allows addition of additional config inside the location block.

I'm unsure how to make this clear in the text, are you able to help

**Comment by ljarzynski** [comment]
@dgodd For sure! Thanks for the clarification. I can make a small update.

**Comment by ljarzynski** [comment]
Thanks, @dgodd !

**Pull request merged**
