### PR TITLE
Dotnet update

### PR DESCRIPTION
**Pull request by tylerphelan**
Update Dotnet Core docs with recommended app workflows:
- Framework Dependent
- Source-based
- Self contained

### CODE REVIEW

**Comment by tylerphelan** [comment]
Sorry for the confusion I accidentally closed this pull request. This is the correctly updated Dotnet docs with the different user workflows. Also, I am in the Pivotal-Cf org and I've submitted other PRs before I should be covered under the Corporate CLA.

**Comment by vikafed** [comment]
Hi @tylerphelan. Thank you for filing this PR! We recently worked with the Windows team to update the .NET Core Buildpack topic: https://docs.cloudfoundry.org/buildpacks/dotnet-core/index.html. We would like to incorporate your changes, but we are not sure how to fit them in. Could you take a look at the revised topic and make a new PR if you see any content you would like to improve?

**Comment by tylerphelan** [comment]
@vikafed we will update this PR so that it does not have conflicts. Thanks for the heads up!

**Comment by Ben16** [comment]
Hi @vikafed,

We've resolved all of the conflicts and added additional changes to reflect the most updated dotnet workflow.

**Comment by vikafed** [comment]
Thanks, @Ben16.

**Pull request merged**
