### PR TITLE
Upgrade to Python 3.5.2

### PR DESCRIPTION
**Pull request by cclauss**
To stay in sync with the buildpack

### CODE REVIEW

**Comment by cclauss** [comment]
I submitted CLA over the weekend.

**Comment by bentarnoff** [comment]
Hi, @cclauss, I'm afraid we're still not showing your status as having signed the CLA. Are you able to [publicize](https://help.github.com/articles/publicizing-or-concealing-organization-membership/) your membership? If not, we may have to wait a little longer for the CLA to "register". Thanks.

**Comment by cclauss** [comment]
This CLA was approved on 18 July 2016.

**Comment by pspinrad** [comment]
Thanks, @cclauss!

**Pull request merged**
