### PR TITLE
Add HTTP/2 configuration to Staticfile docs

### PR DESCRIPTION
**Pull request by Gerg**
- Implementation PR: https://github.com/cloudfoundry/staticfile-buildpack/pull/254

[cloudfoundry/routing-release#200]

cc @robdimsdale

### CODE REVIEW

**Comment by robdimsdale** [comment]
cc @menehune23

**Comment by mjgutermuth** [comment]
Thanks @Gerg! I just saw your note above @robdimsdale--is this ready to merge? If not, I can revert. Thanks!

**Comment by menehune23** [comment]
@mjgutermuth My understanding is that it was safe to merge. Correct me if I'm wrong @robdimsdale

**Comment by robdimsdale** [comment]
Should be fine. I was waiting until we shipped the buildpack before merging the notes so they didn't describe a feature that hadn't shipped yet. We shipped the buildpack so the notes are good to go. Thanks for checking @mjgutermuth !

**Pull request merged**
