### PR TITLE
link to community buildpacks

### PR DESCRIPTION
**Pull request by afeld**
There are probably others out there that I don't know about...just wanted to get a list going. Thanks!

### CODE REVIEW

**Comment by jncd** [comment]
Thank you @afeld !

**Comment by RochesterinNYC** [comment]
Worth noting that there's a list available here: https://github.com/cloudfoundry-community/cf-docs-contrib/wiki/Buildpacks

Not sure how up to date it is though.

**Comment by afeld** [comment]
Hmm, there should probably be a single list. Anyone have strong feelings about which to use?

**Comment by jncd** [comment]
Hi Aidan @afeld ,
James and I were thinking that the list should stay on the community page and that I'd put a link to the community page from the main buildpacks page. 
I'll add the missing buildpacks from your list to the community page.

**Pull request merged**
