### PR TITLE
Add some documentation for richer HSTS support

### PR DESCRIPTION
**Pull request by rogeruiz**
cloudfoundry/staticfile-buildpack#111 :eyes:

### CODE REVIEW

**Comment by seviet** [comment]
Thank you @rogeruiz!

**Comment by sclevine** [comment]
@seviet Reverting. The PR that adds this functionality has not been merged yet.

**Comment by rogeruiz** [comment]
Thanks @sclevine

**Comment by seviet** [comment]
Sorry about that @rogeruiz and @sclevine. Despite the eyes emoji icon, I totally overlooked the link to your related PR. This time, we'll wait for your thumbs up to merge!

**Comment by dgodd** [comment]
@seviet This has now been released as https://github.com/cloudfoundry/staticfile-buildpack/releases/tag/v1.4.14 ; Could you please Add the documentation back.

**Comment by seviet** [comment]
OK @dgodd!

**Pull request merged**
